/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'Lab_5_FSM' 
 * Target:  'Lab_FSM' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device&Standalone:STM32Cube LL:COMMON@1.11.3 */
#define USE_FULL_LL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
