/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'Lab_FSM' 
 * Target:  'Lab_FSM' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f3xx.h"

/* Keil::Compiler&ARM Compiler:I/O:STDOUT&ITM@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_ITM      /* Compiler I/O: STDOUT ITM */
/* Keil::Device&Standalone:STM32Cube LL:COMMON@1.11.3 */
#define RTE_DEVICE_LL_DRIVERS_USED
#define RTE_DEVICE_LL_COMMON
/* Keil::Device&Standalone:STM32Cube LL:DMA@1.11.3 */
#define RTE_DEVICE_LL_DMA
/* Keil::Device&Standalone:STM32Cube LL:GPIO@1.11.3 */
#define RTE_DEVICE_LL_GPIO
/* Keil::Device&Standalone:STM32Cube LL:I2C@1.11.3 */
#define RTE_DEVICE_LL_I2C
/* Keil::Device&Standalone:STM32Cube LL:PWR@1.11.3 */
#define RTE_DEVICE_LL_PWR
/* Keil::Device&Standalone:STM32Cube LL:RCC@1.11.3 */
#define RTE_DEVICE_LL_RCC
/* Keil::Device&Standalone:STM32Cube LL:USART@1.11.3 */
#define RTE_DEVICE_LL_USART
/* Keil::Device&Standalone:STM32Cube LL:UTILS@1.11.3 */
#define RTE_DEVICE_LL_UTILS
/* Keil::Device&Standalone:Startup@1.11.3 */
#define RTE_DEVICE_STARTUP_STM32F3XX    /* Device Startup for STM32F3 */


#endif /* RTE_COMPONENTS_H */
